#ifndef _GAME_DATA_PROVIDER_SERVICE_LOGGER_H
#define _GAME_DATA_PROVIDER_SERVICE_LOGGER_H

#define LOGGER_PROJECT_NAME_SIGNATURE "gdp_dll"
#include "logger/logger.h"

#endif //_GAME_DATA_PROVIDER_SERVICE_LOGGER_H
